"""empty message

Revision ID: 24ada26fa367
Revises: 
Create Date: 2025-02-20 17:13:22.097934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ada26fa367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('EID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('exam_title', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('center', sa.String(), nullable=False),
    sa.Column('booklet', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('question_answer', sa.String(), nullable=False),
    sa.Column('suspicious_activity', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('EID')
    )
    op.create_table('registration',
    sa.Column('RID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('RID')
    )
    op.create_table('student',
    sa.Column('SID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('student_password', sa.String(), nullable=False),
    sa.Column('student_wallet_address', sa.String(), nullable=False),
    sa.Column('student_private_key', sa.String(), nullable=False),
    sa.Column('student_mnemonic', sa.String(), nullable=False),
    sa.Column('student_deployed_app_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('SID'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('registration')
    op.drop_table('exam')
    # ### end Alembic commands ###
