"""empty message

Revision ID: 782154d72a30
Revises: 
Create Date: 2025-01-21 10:55:22.270871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782154d72a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_password', sa.String(), nullable=False),
    sa.Column('student_wallet_address', sa.String(), nullable=False),
    sa.Column('student_private_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
