"""empty message

Revision ID: 9cc242e3d313
Revises: 
Create Date: 2025-01-27 12:41:33.357360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc242e3d313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('SID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('student_password', sa.String(), nullable=False),
    sa.Column('student_wallet_address', sa.String(), nullable=False),
    sa.Column('student_private_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('SID'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
