"""empty message

Revision ID: b59765a89045
Revises: 
Create Date: 2025-01-23 12:23:10.375892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59765a89045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('student_password', sa.String(), nullable=False),
    sa.Column('student_wallet_address', sa.String(), nullable=False),
    sa.Column('student_private_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
