"""empty message

Revision ID: d31ebc552fc1
Revises: 
Create Date: 2025-01-30 14:00:35.104244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31ebc552fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('SID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('student_password', sa.String(), nullable=False),
    sa.Column('student_wallet_address', sa.String(), nullable=False),
    sa.Column('student_private_key', sa.String(), nullable=False),
    sa.Column('student_mnemonic', sa.String(), nullable=False),
    sa.Column('student_deployed_app_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('SID'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
